server:
  port: 8761

spring:
  application:
    name: Eureka   # simpler & consistent naming

eureka:
  client:
    register-with-eureka: false   # Eureka server should not register itself
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info   # safer than "*"
  endpoint:
    health:
      show-details: always    # removed invisible character
